export enum DiscordRPCEvents {
  SPEAKING_START = "SPEAKING_START",
  SPEAKING_STOP = "SPEAKING_STOP",
  VOICE_STATE_CREATE = "VOICE_STATE_CREATE",
  VOICE_STATE_DELETE = "VOICE_STATE_DELETE",
  VOICE_STATE_UPDATE = "VOICE_STATE_UPDATE",
  GET_CHANNEL = "GET_CHANNEL",
  GUILD_STATUS = "GUILD_STATUS",
  ERROR = "ERROR",
  AUTHENTICATE = "AUTHENTICATE",
}

export enum DiscordCMDEvents {
  DISPATCH = "DISPATCH",
  AUTHENTICATE = "AUTHENTICATE",
  GET_GUILDS = "GET_GUILDS",
}
