name: CI/CD

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

env:
  NODE_VERSION: "16"
  CSC_LINK: "${{ secrets.CSC_LINK }}"
  CSC_KEY_PASSWORD: "${{ secrets.CSC_KEY_PASSWORD }}"
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"
  APPLE_ID: "${{ secrets.APPLE_ID }}"
  APPLE_PASSWORD: "${{ secrets.APPLE_PASSWORD }}"

jobs:
  build-mac:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install deps
        run: npm ci
      - name: Build react
        run: npm run build
      - name: Package
        run: npm run pack
      - uses: actions/upload-artifact@v2
        with:
          name: "overlayed-unstable-mac"
          path: "dist/**/*.dmg"
  build-windows:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install deps
        run: npm ci
      - name: Build react
        run: npm run build
      - name: Package
        run: npm run pack
      - uses: actions/upload-artifact@v2
        with:
          name: "overlayed-unstable-windows"
          path: "dist/**/*.msi"
  build-linux:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install deps
        run: npm ci
      - name: Build react
        run: npm run build
      - name: Package
        run: npm run pack
      - uses: actions/upload-artifact@v2
        with:
          name: "overlayed-unstable-linux"
          path: "dist/**/*.zip"
