name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: package
        run: |
          npm ci
          npm run build
          npm run pack

      - uses: actions/upload-artifact@v2
        with:
          name: overlated-unstable
          path: "dist/win-unpacked/*"
