name: CI

on: 
  workflow_dispatch:
  push:

env:
  NODE_VERSION: "16"

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: package
        run: |
          npm ci
          npm run build
          npm run pack
      - uses: actions/upload-artifact@v2
        with:
          name: "overlayed-unstable-${{ matrix.os }}"
          path: "dist/**/*.zip"
      # see if we can just do this here since the bin is already getting built
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
