name: Release

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  NODE_VERSION: "16"

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install deps
        run: npm ci
      - name: Build react
        run: npm run build
      - name: Package
        run: npm run pack
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/**/*.zip"